Repository algolia/algoliasearch-client-php, pull requests merged in 2018-12, with the labels that each got.

#493 Introduce Get/Set Strategy for Personalization
  src/SearchClient.php
Labels: API feature

#488 Remove ensureObjectID for Client::multipleBatch
  src/SearchClient.php
  tests/Integration/MultipleIndexTest.php
Labels: Bug

#499 [2.1.2] Adds `null` resilience to search $query
  src/PlacesClient.php
  src/SearchClient.php
  src/SearchIndex.php
  tests/Unit/RequestTestCase.php
  tests/Unit/SearchTest.php
Labels: Ready
